routes/web.php
<?php

 
Auth::routes(); 
Route::get('/','HomeController@index');
Route::view('createcoord','coord/create')->name('createcoord')->middleware('coord'); //Formulário Coordenador
Route::post('submit','CoordenadorController@store')->middleware('coord');  //Salvar dados do Coordenador no Banco de Dados
Route::get('listcoord','CoordenadorController@listCoord')->name('listcoord')->middleware('coord');  //Página do Coordenador para o Coordenador
Route::get('showcoord/{id}','CoordenadorController@showCoord')->name('showcoord')->middleware('coord'); //Ação de mostrar dados apenas para coordenador
Route::view('createpesq','pesq/create')->name('createpesq')->middleware ('pesq'); //Formulário do Pesquisador
Route::post('submit1','PesquisadorController@store')->middleware('pesq'); //Salvar dados do Pesquisador no Banco de Dados
Route::get('listpesq','PesquisadorController@listUser')->name('listpesq')->middleware('pesq');  //Página do pesquisador para o Pesquisador
Route::get('showpesq/{id}','PesquisadorController@showPesq')->name('showpesq')->middleware('pesq'); //Ação de mostrar dados apenas para pesquisador
Route::resource('dashadmin','ViewController');//->middleware('admin'); //DashBoard do Admin
Route::resource('admin','AdminController')->middleware('admin');
Route::resource('coord','CoordenadorController')->middleware('admin'); //Página do Coordenador para o ADM
Route::resource('pesq','PesquisadorController')->middleware('admin'); //Página do pesquisador para o ADM
Route::delete('deletecoord/{id}','CoordenadorController@destroyCoord')->name('destroycoord')->middleware('coord'); //Ação de mostrar dados apenas para coordenador
Route::delete('deletepesq/{id}','PesquisadorController@destroyPesq')->name('destroypesq')->middleware('pesq'); //Ação de mostrar dados apenas para coordenador

resources/views/coord/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'FAPERN') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('#') }}">
                    {{ config('app.name', 'FAPERN') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Entrar') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Registrar') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Sair') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/coord/edit.blade.php
@extends('../layouts.admin')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Editar Coordenadores</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('coord.index') }}">Voltar</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Ops!</strong> Algum problema ocorreu com sua entrada<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('coord.update',$coord->id) }}" method="POST">
        @csrf
        @method('PUT')
   
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>q1:</strong>
                    <input type="text" name="q1" value="{{ $coord->q1 }}" class="form-control" placeholder="q1">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>q2:</strong>
<input type="text" name="q2" value="{{ $coord->q2 }}" class="form-control" placeholder="q2">
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>q3:</strong>
<input type="text" name="q3" value="{{ $coord->q3 }}" class="form-control" placeholder="q3">
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>q4:</strong>
<input type="text" name="q4" value="{{ $coord->q4 }}" class="form-control" placeholder="q4">
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>q5:</strong>
<input type="text" name="q5" value="{{ $coord->q5 }}" class="form-control" placeholder="q5">
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>q6:</strong>
<input type="text" name="q6" value="{{ $coord->q6 }}" class="form-control" placeholder="q6">
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>q7:</strong>
<input type="text" name="q7" value="{{ $coord->q7 }}" class="form-control" placeholder="q7">
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>q8:</strong>
<input type="text" name="q8" value="{{ $coord->q8 }}" class="form-control" placeholder="q8">
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>q9:</strong>
<input type="text" name="q9" value="{{ $coord->q9 }}" class="form-control" placeholder="q9">
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>q10:</strong>
<input type="text" name="q10" value="{{ $coord->q10 }}" class="form-control" placeholder="q10">
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>q11:</strong>
<input type="text" name="q11" value="{{ $coord->q11 }}" class="form-control" placeholder="q11">
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>q12:</strong>
<input type="text" name="q12" value="{{ $coord->q12 }}" class="form-control" placeholder="q12">
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>q13:</strong>
<input type="text" name="q13" value="{{ $coord->q13 }}" class="form-control" placeholder="q13">
</div>
</div>
            <div class="'col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
   
    </form>
@endsection

resources/views/coord/list.blade.php
@extends('coord.app')

@section('content')

<div class="form-row text-right">
    <div class="col-10">
        <a class="btn btn-primary" href="{{ url('dashadmin') }}">Voltar</a>
    </div>
 </div>
<br>

<div class="row justify-content-center">
    <div class="col-md-10">
        <div class="card">
            <div class="card-header"><h3>Coordenadores</h3></div>
            <div class="card-body">

    @if ($message = Session::get('message'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table id="coord" class="table table-bordered">
        <thead>
        <tr>
            <th>Coordenador</th>
            <th>Nº da Pesquisa</th>
            <th>Data</th>
            <th>Hora</th>
            <th width="350px">Ação</th>
        </tr>
    <thead>
        @foreach ($coord as $cd)
        <tr>
                 
            <td>{{ $cd->user->name}}</td>
            <td>{{ $loop->iteration }}</td>
            <td>{{date('d-m-Y', strtotime($cd->created_at))}}</td>
            <td>{{date('H:i:s', strtotime($cd->created_at))}}</td>
            

           

            <td>
            <form action="{{ route('coord.destroy',$cd->id) }}" method="POST">
   
                    <a class="btn btn-info" href="{{ route('coord.show',$cd->id) }}">Visualizar</a>
                    {{-- <a class="btn btn-primary" href="{{ route('coord.edit',$cd->id) }}">Editar</a> --}}

        
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Deletar</button>
                </form>
            </td>
        </tr>
    </tbody>
        @endforeach
    </table>

    {!! $coord->links() !!}

</div>
</div>
</div>
</div>
       
@endsection

resources/views/coord/list_coord.blade.php
@extends('coord.app')
 
@section('content')

<div class="form-row text-right">
    <div class="col-10">
        <a class="btn btn-primary" href="{{ route('createcoord') }}">Responder Questionário</a>
    </div>
 </div>
<br>

<div class="row justify-content-center">
    <div class="col-md-10">
        <div class="card">
            <div class="card-header"><h3>Meu Questionário</h3></div>
            <div class="card-body">

    @if ($message = Session::get('message'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table id="coord" class="table table-bordered">
        <thead>
        <tr>
            <th>Pesquisador</th>
            <th>Nº da Pesquisa</th>
            <th>Data</th>
            <th>Hora</th>
            <th width="350px">Ação</th>
        </tr>
    <thead>
        @foreach ($coord as $cd)
        <tr>
                 
            <td>{{ $cd->user->name}}</td>
            <td>{{ $loop->iteration }}</td>
            <td>{{date('d-m-Y', strtotime($cd->created_at))}}</td>
            <td>{{date('H:i:s', strtotime($cd->created_at))}}</td>
            

           

            <td>
            <form action="{{ route('destroycoord',$cd->id) }}" method="POST">
   
                    <a class="btn btn-info" href="{{ route('showcoord',$cd->id) }}">Visualizar</a>

                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Deletar</button>
                </form>
            </td>
        </tr>
    </tbody>
        @endforeach
    </table>
</div>
</div>
</div>
</div>
       
@endsection

resources/views/coord/show.blade.php
@extends('../layouts.admin')

@section('content')
<title>FAPERN</title>
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
            </div>
            <div class="pull-right">
                <button onClick="window.print()" a class="btn btn-primary" >Imprimir Formulário</button></a>
                <a class="btn btn-primary" href="{{ route('coord.index') }}">Voltar</a>
            </div>
        </div>
    </div>

    <table class="table" .table> 
        <tr>
            <td>
<h5>Olá, {{$coord->user->name}}!<br>CPF: {{$coord->user->cpf}}<br>E-mail: {{$coord->user->email}}<br>{{$coord->user->edital}}</h5>
            </td>       
</tr>
<td>
<tr>
    <h1>Comprovante de Inscrição de Nº: {{$coord->id}}</h1>
</td>
</tr>
</table>
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>1. Quantidade de projetos de pesquisa vinculados ao órgão?</strong><br>
                <strong>Reposta:</strong> {{ $coord->q1 }}
            </div>
        </div>

       
        <div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>2.	Todas as pesquisas estão em desenvolvimento de acordo com o cronograma?</strong><br>
<strong>Reposta:</strong> {{ $coord->q2}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>3. Digite a quantidade de projetos que não está em desenvolvimento. </strong>(Caso todos os projetos estejam em execução, indicar o número 0 no campo abaixo).<br>
<strong>Reposta:</strong> {{ $coord->q3}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>4. Houve mudanças no objeto de algum projeto entre a aprovação e o início do desenvolvimento?</strong><br>
<strong>Reposta:</strong> {{ $coord->q4}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>5. Em qual/quais aspecto/s os projetos tiveram mudanças?</strong> (múltipla escolha)<br>
<strong>Reposta:</strong> {{ $coord->q5}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>6. Tem sido possível acompanhar/orientar adequadamente as pesquisas? </strong><br>
<strong>Reposta:</strong> {{ $coord->q6}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>7.	 Caso não tenha sido possível acompanhar adequadamente as pesquisas, informe o/os motivo/s.</strong> (múltipla escolha)<br>
<strong>Reposta:</strong> {{ $coord->q7}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>8. A carga horária semanal do pesquisador é suficiente para o desenvolvimento do projeto de pesquisa?</strong><br>
<strong>Reposta:</strong> {{ $coord->q8}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>9. Qual a frequência de encontros de orientação?</strong><br>
<strong>Reposta:</strong> {{ $coord->q9}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>10. O/os relatório/s foi/foram produzido/s?</strong><br>
<strong>Reposta:</strong> {{ $coord->q10}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>11.	Indique o nível de satisfação relacionado à inovação proporcionada ao órgão</strong><br>
<strong>Reposta:</strong> {{ $coord->q11}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>12.	Indique o nível de satisfação relacionado ao desempenho do pesquisador.</strong><br>
<strong>Reposta:</strong> {{ $coord->q12}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>13.	Espaço reservado para anotações sobre as questões acima, sugestões e dúvidas em geral. </strong><br>
<strong>Reposta:</strong> {{ $coord->q13}}
</div>
</div>

@endsection

resources/views/coord/show_coord.blade.php
@extends('../layouts.admin')

@section('content')
<title>FAPERN</title>
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
            </div>
            <div class="pull-right">
                <button onClick="window.print()" a class="btn btn-primary" >Imprimir Formulário</button></a>
                <a class="btn btn-primary" href="{{url()->previous()}}">Voltar</a>
            </div>
        </div>
    </div>

    <table class="table" .table> 
        <tr>
            <td>
<h5>Olá, {{$coord->user->name}}!<br>CPF: {{$coord->user->cpf}}<br>E-mail: {{$coord->user->email}}<br>{{$coord->user->edital}}</h5>
            </td>       
</tr>
<td>
<tr>
    <h1>Comprovante de Inscrição de Nº: {{$coord->id}}</h1>
</td>
</tr>
</table>
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>1. Quantidade de projetos de pesquisa vinculados ao órgão?</strong><br>
                <strong>Reposta:</strong> {{ $coord->q1 }}
            </div>
        </div>

       
        <div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>2.	Todas as pesquisas estão em desenvolvimento de acordo com o cronograma?</strong><br>
<strong>Reposta:</strong> {{ $coord->q2}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>3. Digite a quantidade de projetos que não está em desenvolvimento. </strong>(Caso todos os projetos estejam em execução, indicar o número 0 no campo abaixo).<br>
<strong>Reposta:</strong> {{ $coord->q3}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>4. Houve mudanças no objeto de algum projeto entre a aprovação e o início do desenvolvimento?</strong><br>
<strong>Reposta:</strong> {{ $coord->q4}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>5. Em qual/quais aspecto/s os projetos tiveram mudanças?</strong> (múltipla escolha)<br>
<strong>Reposta:</strong> {{ $coord->q5}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>6. Tem sido possível acompanhar/orientar adequadamente as pesquisas? </strong><br>
<strong>Reposta:</strong> {{ $coord->q6}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>7.	 Caso não tenha sido possível acompanhar adequadamente as pesquisas, informe o/os motivo/s.</strong> (múltipla escolha)<br>
<strong>Reposta:</strong> {{ $coord->q7}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>8. A carga horária semanal do pesquisador é suficiente para o desenvolvimento do projeto de pesquisa?</strong><br>
<strong>Reposta:</strong> {{ $coord->q8}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>9. Qual a frequência de encontros de orientação?</strong><br>
<strong>Reposta:</strong> {{ $coord->q9}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>10. O/os relatório/s foi/foram produzido/s?</strong><br>
<strong>Reposta:</strong> {{ $coord->q10}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>11.	Indique o nível de satisfação relacionado à inovação proporcionada ao órgão</strong><br>
<strong>Reposta:</strong> {{ $coord->q11}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>12.	Indique o nível de satisfação relacionado ao desempenho do pesquisador.</strong><br>
<strong>Reposta:</strong> {{ $coord->q12}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>13.	Espaço reservado para anotações sobre as questões acima, sugestões e dúvidas em geral. </strong><br>
<strong>Reposta:</strong> {{ $coord->q13}}
</div>
</div>

@endsection