routes/web.php
<?php

 
Auth::routes(); 
Route::get('/','HomeController@index');
Route::view('createcoord','coord/create')->name('createcoord')->middleware('coord'); //Formulário Coordenador
Route::post('submit','CoordenadorController@store')->middleware('coord');  //Salvar dados do Coordenador no Banco de Dados
Route::get('listcoord','CoordenadorController@listCoord')->name('listcoord')->middleware('coord');  //Página do Coordenador para o Coordenador
Route::get('showcoord/{id}','CoordenadorController@showCoord')->name('showcoord')->middleware('coord'); //Ação de mostrar dados apenas para coordenador
Route::view('createpesq','pesq/create')->name('createpesq')->middleware ('pesq'); //Formulário do Pesquisador
Route::post('submit1','PesquisadorController@store')->middleware('pesq'); //Salvar dados do Pesquisador no Banco de Dados
Route::get('listpesq','PesquisadorController@listUser')->name('listpesq')->middleware('pesq');  //Página do pesquisador para o Pesquisador
Route::get('showpesq/{id}','PesquisadorController@showPesq')->name('showpesq')->middleware('pesq'); //Ação de mostrar dados apenas para pesquisador
Route::resource('dashadmin','ViewController');//->middleware('admin'); //DashBoard do Admin
Route::resource('admin','AdminController')->middleware('admin');
Route::resource('coord','CoordenadorController')->middleware('admin'); //Página do Coordenador para o ADM
Route::resource('pesq','PesquisadorController')->middleware('admin'); //Página do pesquisador para o ADM
Route::delete('deletecoord/{id}','CoordenadorController@destroyCoord')->name('destroycoord')->middleware('coord'); //Ação de mostrar dados apenas para coordenador
Route::delete('deletepesq/{id}','PesquisadorController@destroyPesq')->name('destroypesq')->middleware('pesq'); //Ação de mostrar dados apenas para coordenador

resources/views/admin/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Editar dados do Usuário</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>
<body>
  
<div class="container">
    @yield('content')
</div>
   
</body>
</html>

resources/views/admin/edit.blade.php
@extends('admin.app')
   
@section('content')

           
 <br>
                
 <div class="pull-center">
    <a class="btn btn-primary" href="{{url()->previous()}}">Voltar</a>
</div>

<br>
           
<div class="row justify-content-center">
    <div class="col-4" align-self-center”>
        <div class="card">
            <div class="card-header"><h3>Editar Usuário</h3></div>
            <div class="card-body">       
            </div>
        </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Ops!</strong>Aconteceu algum erro com sua entrada.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('admin.update',$admin->id) }}" method="POST">
        @csrf
        @method('PUT')
   
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Nome:</strong>
                    <input type="text" name="name" value="{{ $admin->name }}" class="form-control" placeholder="Name">
                </div>

                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>CPF:</strong>
                            <input type="number" name="cpf" value="{{ $admin->cpf }}" class="form-control" placeholder="CPF">
                        </div>

         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Telefone:</strong>
                    <input type="text" name="telefone" value="{{ $admin->telefone }}" class="form-control" placeholder="Telefone">
                </div>

                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>E-mail:</strong>
                            <input type="text" name="email" value="{{ $admin->email }}" class="form-control" placeholder="Email">
                        </div>

                        
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Função:</strong>
                            <input type="text" name="funcao" value="{{ $admin->funcao }}" class="form-control" placeholder="Função">
                        </div>

                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Edital:</strong>
                                <input type="text" name="edital" value="{{ $admin->edital }}" class="form-control" placeholder="Edital">
                            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Enviar</button>
              <br><br>
            </div>
        </div>
      

    </form>
@endsection

resources/views/admin/index.blade.php
@extends('admin.layout')


<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">


@section('content')
    
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <span class="glyphicon glyphicon-bookmark"></span> Menu</h3>
                </div>
                <div class="panel-body">
                    <div class="row ">
                       
                      <div class="col-xs-8 col-md-12">
                        <a href="{{ url('pesq') }}" class="btn btn-success btn-lg" role="button"><span class="glyphicon glyphicon-user"></span> <br/>Pesquisador</a>
                        <a href="{{ url('coord') }}" class="btn btn-info btn-lg" role="button"><span class="glyphicon glyphicon-file"></span> <br/>Coordenadores</a>
                        <a href="{{ url('admin') }}" class="btn btn-primary btn-lg" role="button"><span class="glyphicon glyphicon-th-list"></span> <br/>Todos Usuários</a>
                        <a href="#" class="btn btn-warning btn-lg" role="button"><span class="glyphicon glyphicon-stats"></span> <br/>Gráficos</a>
                        <a href="#" class="btn btn-primary btn-lg" role="button"><span class="glyphicon glyphicon-th-list"></span> <br/>E-mails</a>
                        <a href="#" class="btn btn-info btn-lg" role="button"><span class="glyphicon glyphicon-file"></span> <br/>Estatística</a>

                      </div>
                      
                      {{-- <div class="col-xs-6 col-md-6">
                          <a href="#" class="btn btn-danger btn-lg" role="button"><span class="glyphicon glyphicon-list-alt"></span> <br/>Apps</a>
                          <a href="#" class="btn btn-warning btn-lg" role="button"><span class="glyphicon glyphicon-bookmark"></span> <br/>Bookmarks</a>
                          <a href="#" class="btn btn-primary btn-lg" role="button"><span class="glyphicon glyphicon-signal"></span> <br/>Reports</a>
                          <a href="#" class="btn btn-primary btn-lg" role="button"><span class="glyphicon glyphicon-comment"></span> <br/>Comments</a>
                        </div> --}}
                       
                    </div>
                    {{-- <a href="#" class="btn btn-success btn-lg btn-block" role="button"><span class="glyphicon glyphicon-globe"></span> Website</a> --}}
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/layout.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'FAPERN') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
   
<style>
   
    .panel-body .btn:not(.btn-block) { 
    width:200px;
    margin-bottom:40px; 
    margin-left: 130px;
    font-size: 1.800rem;
    }

    .navbar-brand {
    font-size: 1.800rem;
}

body {
    margin: 0;
    font-family: "Nunito", sans-serif;
    font-size: 1.300rem;
}

.dropdown-menu {
  font-size: 1.4rem;
}
    </style> 
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'FAPERN') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Entrar') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Registrar') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Sair') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>


</body>
</html>

resources/views/admin/list.blade.php
@extends('../coord.app')

@section('content')

<div class="form-row text-right">
    <div class="col-10">
        <a class="btn btn-primary" href="{{ url('dashadmin') }}">Voltar</a>
    </div>
 </div>
<br>

 
<div class="row justify-content-center">
    <div class="col-md-10">
        <div class="card">
            <div class="card-header"><h3>Usuários Cadastrados</h3></div>
            <div class="card-body">
    
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table table-bordered">
        <tr>
            <th>No</th>
            <th>Nome</th>
            <th>CPF</th> 
            <th>E-mail</th> 
            <th>Telefone</th> 
            <th>Função</th> 
            <th>Edital</th>    
            <th width="350px">Ação</th>
        </tr>
        @foreach ($admin as $adm)
        <tr>
            <td>{{ $loop->iteration }}</td>
            <td>{{ $adm->name }}</td>
            <td>{{ $adm->cpf }}</td>
            <td><a href="mailto:{{$adm->email}}">{{$adm->email}}</a></td>
            <td>{{ $adm->telefone }}</td>
            <td>{{ $adm->funcao }}</td>
            <td>{{ $adm->edital }}</td>
            <td>
                <form action="{{ route('admin.destroy',$adm->id) }}" method="POST">
   
                    {{-- <a class="btn btn-info" href="{{ route('admin.show',$adm->id) }}">Mostrar</a> --}}
    
                    <a class="btn btn-primary" href="{{ route('admin.edit',$adm->id) }}">Editar</a>
    
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Deletar</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
        
@endsection