routes/web.php
<?php

 
Auth::routes(); 
Route::get('/','HomeController@index');
Route::view('createcoord','coord/create')->name('createcoord')->middleware('coord'); //Formulário Coordenador
Route::post('submit','CoordenadorController@store')->middleware('coord');  //Salvar dados do Coordenador no Banco de Dados
Route::get('listcoord','CoordenadorController@listCoord')->name('listcoord')->middleware('coord');  //Página do Coordenador para o Coordenador
Route::get('showcoord/{id}','CoordenadorController@showCoord')->name('showcoord')->middleware('coord'); //Ação de mostrar dados apenas para coordenador
Route::view('createpesq','pesq/create')->name('createpesq')->middleware ('pesq'); //Formulário do Pesquisador
Route::post('submit1','PesquisadorController@store')->middleware('pesq'); //Salvar dados do Pesquisador no Banco de Dados
Route::get('listpesq','PesquisadorController@listUser')->name('listpesq')->middleware('pesq');  //Página do pesquisador para o Pesquisador
Route::get('showpesq/{id}','PesquisadorController@showPesq')->name('showpesq')->middleware('pesq'); //Ação de mostrar dados apenas para pesquisador
Route::resource('dashadmin','ViewController');//->middleware('admin'); //DashBoard do Admin
Route::resource('admin','AdminController')->middleware('admin');
Route::resource('coord','CoordenadorController')->middleware('admin'); //Página do Coordenador para o ADM
Route::resource('pesq','PesquisadorController')->middleware('admin'); //Página do pesquisador para o ADM
Route::delete('deletecoord/{id}','CoordenadorController@destroyCoord')->name('destroycoord')->middleware('coord'); //Ação de mostrar dados apenas para coordenador
Route::delete('deletepesq/{id}','PesquisadorController@destroyPesq')->name('destroypesq')->middleware('pesq'); //Ação de mostrar dados apenas para coordenador

resources/views/pesq/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'FAPERN') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('#gir') }}">
                    {{ config('app.name', 'FAPERN') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Entrar') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Registrar') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Sair') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/pesq/edit.blade.php
@extends('pesq.app')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Editar Questões</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('pesq.index') }}">Voltar</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Ops!</strong> Algum problema ocorreu com sua entrada<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('pesq.update',$pesq->id) }}" method="POST">
        @csrf
        @method('PUT')
   
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>q1:</strong>
                    <input type="text" name="q1" value="{{ $pesq->q1 }}" class="form-control" placeholder="q1">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>q2:</strong>
<input type="text" name="q2" value="{{ $pesq->q2 }}" class="form-control" placeholder="q2">
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>q3:</strong>
<input type="text" name="q3" value="{{ $pesq->q3 }}" class="form-control" placeholder="q3">
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>q4:</strong>
<input type="text" name="q4" value="{{ $pesq->q4 }}" class="form-control" placeholder="q4">
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>q5:</strong>
<input type="text" name="q5" value="{{ $pesq->q5 }}" class="form-control" placeholder="q5">
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>q6:</strong>
<input type="text" name="q6" value="{{ $pesq->q6 }}" class="form-control" placeholder="q6">
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>q7:</strong>
<input type="text" name="q7" value="{{ $pesq->q7 }}" class="form-control" placeholder="q7">
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>q8:</strong>
<input type="text" name="q8" value="{{ $pesq->q8 }}" class="form-control" placeholder="q8">
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>q9:</strong>
<input type="text" name="q9" value="{{ $pesq->q9 }}" class="form-control" placeholder="q9">
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>q10:</strong>
<input type="text" name="q10" value="{{ $pesq->q10 }}" class="form-control" placeholder="q10">
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>q11:</strong>
<input type="text" name="q11" value="{{ $pesq->q11 }}" class="form-control" placeholder="q11">
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>q12:</strong>
<input type="text" name="q12" value="{{ $pesq->q12 }}" class="form-control" placeholder="q12">
</div>
</div>


<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>q13:</strong>
<input type="text" name="q13" value="{{ $pesq->q13 }}" class="form-control" placeholder="Questão 13">
</div>
</div>

<div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group">
    <strong>q14:</strong>
    <input type="text" name="q14" value="{{ $pesq->q14 }}" class="form-control" placeholder="Questão 14">
    </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
        <strong>q15:</strong>
        <input type="text" name="q15" value="{{ $pesq->q15 }}" class="form-control" placeholder="Questão 15">
        </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
            <strong>q16:</strong>
            <input type="text" name="q16" value="{{ $pesq->q16 }}" class="form-control" placeholder="Questão 16">
            </div>
            </div>
            
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
            <strong>q17:</strong>
            <input type="text" name="q17" value="{{ $pesq->q17 }}" class="form-control" placeholder="Questão 17">
            </div>
            </div>
            

<div class="'col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
   
    </form>
@endsection

resources/views/pesq/list.blade.php
@extends('pesq.app')
 
@section('content')

<div class="form-row text-right">
    <div class="col-10">
        <a class="btn btn-primary" href="{{ url('dashadmin') }}">Voltar</a>
    </div>
 </div>
<br>

<div class="row justify-content-center">
    <div class="col-md-10">
        <div class="card">
            <div class="card-header"><h3>Pesquisadores</h3></div>
            <div class="card-body">

    @if ($message = Session::get('message'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table id="pesq" class="table table-bordered">
        <thead>
        <tr>
            <th>Pesquisador</th>
            <th>Nº da Pesquisa</th>
            <th>Data</th>
            <th>Hora</th>
            <th width="350px">Ação</th>
        </tr>
    <thead>
        @foreach ($pesq as $ps)
        <tr>
                 
            <td>{{ $ps->user->name}}</td>
            <td>{{ $ps->id }}</td>
            <td>{{date('d-m-Y', strtotime($ps->created_at))}}</td>
            <td>{{date('H:i:s', strtotime($ps->created_at))}}</td>
            

           

            <td>
            <form action="{{ route('pesq.destroy',$ps->id) }}" method="POST">
   
                    <a class="btn btn-info" href="{{ route('pesq.show',$ps->id) }}">Visualizar</a>
                    {{-- <a class="btn btn-primary" href="{{ route('pesq.edit',$ps->id) }}">Editar</a> --}}

        
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Deletar</button>
                </form>
            </td>
        </tr>
    </tbody>
        @endforeach
    </table>
    {!! $pesq->links() !!}
</div>
</div>
</div>
</div>
       
@endsection

resources/views/pesq/list_user.blade.php
@extends('pesq.app')

@section('content')

  <div class="form-row text-right">
    <div class="col-10">
        <a class="btn btn-primary" href="{{ route('createpesq') }}">Responder Questionário</a>
    </div>
 </div>
<br>

<div class="row justify-content-center">
    <div class="col-md-10">
        <div class="card">
            <div class="card-header"><h3>Meu Questionário</h3></div>
            <div class="card-body">

    @if ($message = Session::get('message'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table id="pesq" class="table table-bordered">
        <thead>
        <tr>
            <th>Pesquisador</th>
            <th>Nº da Pesquisa</th>
            <th>Data</th>
            <th>Hora</th>
            <th width="350px">Ação</th>
        </tr>
    <thead>
        @foreach ($pesq as $ps)
        <tr>
                 
            <td>{{ $ps->user->name}}</td>
            <td>{{ $loop->iteration }}</td>
            <td>{{date('d-m-Y', strtotime($ps->created_at))}}</td>
            <td>{{date('H:i:s', strtotime($ps->created_at))}}</td>
            

           

            <td>
            <form action="{{ route('destroypesq',$ps->id) }}" method="POST">
   
                    <a class="btn btn-info" href="{{ route('showpesq',$ps->id) }}">Visualizar</a>
        
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Deletar</button>
                </form>
            </td>
        </tr>
    </tbody>
        @endforeach
    </table>
</div>
</div>
</div>
</div>
       
@endsection

resources/views/pesq/show.blade.php
@extends('../layouts.admin')

@section('content')
<title>FAPERN</title>
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
            </div>
            <div class="pull-right">
                <button onClick="window.print()" a class="btn btn-primary" >Imprimir Formulário</button></a>
                <a class="btn btn-primary" href="{{url()->previous()}}">Voltar</a>
            </div>  
        </div>
    </div>

    <table class="table" .table> 
        <tr>
            <td>
<h5>Olá, {{$pesq->user->name}}!<br>CPF: {{$pesq->user->cpf}}<br>E-mail: {{$pesq->user->email}}<br>{{$pesq->user->edital}}</h5>
            </td>       
</tr>
<td>
<tr>
    <h1>Comprovante de Inscrição de Nº: {{$pesq->id}}</h1>
</td>
</tr>
</table>
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>1. A pesquisa já foi iniciada?</strong><br>
                <strong>Reposta:</strong> {{ $pesq->q1 }}
            </div>
        </div>

       
        <div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>2. Em caso de a pesquisa não ter sido iniciada indique o motivo.</strong><br>
<strong>Reposta:</strong> {{ $pesq->q2}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>3. Houve mudanças no objeto do projeto entre a aprovação e o início do desenvolvimento?</strong><br>
<strong>Reposta:</strong> {{ $pesq->q3}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>4. Em qual/quais aspecto/s o projeto teve mudança?</strong><br>
<strong>Reposta:</strong> {{ $pesq->q4}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>5. Em qual fase de execução encontra-se a pesquisa?</strong><br>
<strong>Reposta:</strong> {{ $pesq->q5}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>6. Será necessária prorrogação de prazo para conclusão da pesquisa?</strong><br>
<strong>Reposta:</strong> {{ $pesq->q6}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>7. Qual motivo leva à solicitação de prorrogação? </strong><br>
<strong>Reposta:</strong> {{ $pesq->q7}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>8.	A pesquisa está sendo acompanhada/orientada? </strong><br>
<strong>Reposta:</strong> {{ $pesq->q8}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>9.	Quem coordena a pesquisa?</strong><br>
<strong>Reposta:</strong> {{ $pesq->q9}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>10.	A carga horária semanal é suficiente para o desenvolvimento do projeto de pesquisa?</strong><br>
<strong>Reposta:</strong> {{ $pesq->q10}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>11.	Qual a periodicidade do acompanhamento por parte do coordenador?</strong><br>
<strong>Reposta:</strong> {{ $pesq->q11}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>12.	O/os relatório/s foi/foram produzido/s?</strong><br>
<strong>Reposta:</strong> {{ $pesq->q12}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>13.	Qual/quais o/os motivo/s que levaram a não entrega do relatório?</strong><br>
<strong>Reposta:</strong> {{ $pesq->q13}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>14.	Há clareza a quem o pesquisador deve se dirigir para sanar dúvidas administrativas do cotidiano (frequência, ajustes de horários, eventos, reuniões, etc)?</strong><br>
<strong>Reposta:</strong> {{ $pesq->q14}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>15.	Indique o nível de satisfação relacionado à execução do proejo de pesquisa.</strong><br>
<strong>Reposta:</strong> {{ $pesq->q15}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>16.	Indique o nível de satisfação relacionado ao acompanhamento do projeto pelo coordenador.</strong><br>
<strong>Reposta:</strong> {{ $pesq->q16}}
</div>
</div>

<div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group">
    <strong>17.	Qual/quais o/os motivo/s que levaram a não entrega do relatório?</strong><br>
    <strong>Reposta:</strong> {{ $pesq->q17}}
    </div>
    </div>
@endsection

resources/views/pesq/show_pesq.blade.php
@extends('../layouts.admin')

@section('content')
<title>FAPERN</title>
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
            </div>
            <div class="pull-right">
                <button onClick="window.print()" a class="btn btn-primary" >Imprimir Formulário</button></a>
                <a class="btn btn-primary" href="{{url()->previous()}}">Voltar</a>
            </div>  
        </div>
    </div>

    <table class="table" .table> 
        <tr>
            <td>
<h5>Olá, {{$pesq->user->name}}!<br>CPF: {{$pesq->user->cpf}}<br>E-mail: {{$pesq->user->email}}<br>{{$pesq->user->edital}}</h5>
            </td>       
</tr>
<td>
<tr>
    <h1>Comprovante de Inscrição de Nº: {{$pesq->id}}</h1>
</td>
</tr>
</table>
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>1. A pesquisa já foi iniciada?</strong><br>
                <strong>Reposta:</strong> {{ $pesq->q1 }}
            </div>
        </div>

       
        <div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>2. Em caso de a pesquisa não ter sido iniciada indique o motivo.</strong><br>
<strong>Reposta:</strong> {{ $pesq->q2}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>3. Houve mudanças no objeto do projeto entre a aprovação e o início do desenvolvimento?</strong><br>
<strong>Reposta:</strong> {{ $pesq->q3}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>4. Em qual/quais aspecto/s o projeto teve mudança?</strong><br>
<strong>Reposta:</strong> {{ $pesq->q4}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>5. Em qual fase de execução encontra-se a pesquisa?</strong><br>
<strong>Reposta:</strong> {{ $pesq->q5}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>6. Será necessária prorrogação de prazo para conclusão da pesquisa?</strong><br>
<strong>Reposta:</strong> {{ $pesq->q6}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>7. Qual motivo leva à solicitação de prorrogação? </strong><br>
<strong>Reposta:</strong> {{ $pesq->q7}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>8.	A pesquisa está sendo acompanhada/orientada? </strong><br>
<strong>Reposta:</strong> {{ $pesq->q8}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>9.	Quem coordena a pesquisa?</strong><br>
<strong>Reposta:</strong> {{ $pesq->q9}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>10.	A carga horária semanal é suficiente para o desenvolvimento do projeto de pesquisa?</strong><br>
<strong>Reposta:</strong> {{ $pesq->q10}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>11.	Qual a periodicidade do acompanhamento por parte do coordenador?</strong><br>
<strong>Reposta:</strong> {{ $pesq->q11}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>12.	O/os relatório/s foi/foram produzido/s?</strong><br>
<strong>Reposta:</strong> {{ $pesq->q12}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>13.	Qual/quais o/os motivo/s que levaram a não entrega do relatório?</strong><br>
<strong>Reposta:</strong> {{ $pesq->q13}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>14.	Há clareza a quem o pesquisador deve se dirigir para sanar dúvidas administrativas do cotidiano (frequência, ajustes de horários, eventos, reuniões, etc)?</strong><br>
<strong>Reposta:</strong> {{ $pesq->q14}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>15.	Indique o nível de satisfação relacionado à execução do proejo de pesquisa.</strong><br>
<strong>Reposta:</strong> {{ $pesq->q15}}
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>16.	Indique o nível de satisfação relacionado ao acompanhamento do projeto pelo coordenador.</strong><br>
<strong>Reposta:</strong> {{ $pesq->q16}}
</div>
</div>

<div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group">
    <strong>17.	Qual/quais o/os motivo/s que levaram a não entrega do relatório?</strong><br>
    <strong>Reposta:</strong> {{ $pesq->q17}}
    </div>
    </div>
@endsection